name: OSBC
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.9
  - pip=23.1.2
  - python=3.11.3
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - accelerate==0.20.3
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.2
      - attrs==23.1.0
      - blis==0.7.9
      - catalogue==2.0.8
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cmake==3.26.4
      - confection==0.0.4
      - cymem==2.0.7
      - datasets==2.13.1
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - en-core-web-sm==3.5.0
      - filelock==3.12.2
      - frozenlist==1.3.3
      - fsspec==2023.6.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - huggingface-hub==0.15.1
      - idna==3.4
      - jinja2==3.1.2
      - joblib==1.2.0
      - langcodes==3.3.0
      - lit==16.0.6
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - murmurhash==1.0.9
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.25.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - packaging==23.1
      - pandas==2.0.2
      - pathtools==0.1.2
      - pathy==0.10.2
      - pillow==9.5.0
      - preshed==3.0.8
      - protobuf==4.23.3
      - psutil==5.9.5
      - pyarrow==12.0.1
      - pydantic==1.10.9
      - pytesseract==0.3.10
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0
      - regex==2023.6.3
      - requests==2.31.0
      - safetensors==0.3.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.26.0
      - setproctitle==1.3.2
      - six==1.16.0
      - smart-open==6.3.0
      - smmap==5.0.0
      - spacy==3.5.3
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - srsly==2.4.6
      - sympy==1.12
      - thinc==8.1.10
      - threadpoolctl==3.1.0
      - tokenizers==0.13.3
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.65.0
      - transformers==4.30.2
      - triton==2.0.0
      - typer==0.7.0
      - typing-extensions==4.6.3
      - tzdata==2023.3
      - urllib3==2.0.3
      - wandb==0.15.4
      - wasabi==1.1.2
      - xxhash==3.2.0
      - yarl==1.9.2
